server:
  port: 8085
spring:
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://127.0.0.1:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: YhTLN4vdqwbfg1gpmAIOYxV2PaVuxPsw
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
              - microprofile-jwt 
            client-id: admin-service
            client-secret: YhTLN4vdqwbfg1gpmAIOYxV2PaVuxPsw
          discovery:
            provider: keycloak
            client-id: admin-service
            client-secret: YhTLN4vdqwbfg1gpmAIOYxV2PaVuxPsw
            authorization-grant-type: client_credentials
            scope:
              - discovery
  application:
    name: selmag-admin-server
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
  client:
    register-with-eureka: false
    registryFetchIntervalSeconds: 1
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/