spring:
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: catalogue-service-route
          uri: lb://selmag-catalogue-service
          predicates:
            - Host=catalogue.api.chernyshov.ignat.127.0.0.1.nip.io:8086
        - id: feedback-service-route
          uri: lb://selmag-feedback-service
          predicates:
            - Host=feadback.api.chernyshov.ignat.127.0.0.1.nip.io:8086
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.109.247:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.109.247:8082/realms/selmag
        registration:
          discovery:
            provider: keycloak
            client-id: api-gateway
            client-secret: kaKBJ6Pc9mPldygbbI5SgWkZWo1ewk5y
            authorization-grant-type: client_credentials
            scope:
              - discovery
  application:
    name: selmag-api-gateway
  boot:
    admin:
      client:
        url: http://127.0.0.1:8085
        instance:
          name: api-gateway
          service-host-type: ip
          service-base-url: http://127.0.0.1:8086
          management-base-url: http://127.0.0.1:8086
        enabled: true
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8086
  forward-headers-strategy: framework
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 1