server:
  port: 8081
spring:
  application:
    name: selmag-catalogue-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@127.0.0.1:8888