server:
  port: 8081
  forward-headers-strategy: native
spring:
  application:
    name: selmag-catalogue-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@172.17.0.1:8888