spring:
  security:
    user:
      name: config
      password: config-password
      roles:
        - CONFIG
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
