selmag:
  service:
    catalogue:
      uri: http://localhost:8081
    feedback:
      uri: http://localhost:8084
server:
  port: 8083
spring:
  application:
    name: selmag-customer-service
  boot:
    admin:
      client:
        url: http://localhost:8085
        instance:
          name: customer-app
          service-host-type: ip
        enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.109.247:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: MbROevnUr8jmr6OQqH0TSvtyuX1ZUSPc
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalogue
          metrics:
            provider: keycloak
            client-id: customer-app-metrics-client
            client-secret: mZONEZYoSl6F3GwH9IurPCl03UrwZ2xz
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
        jwt:
          issuer-uri: http://192.168.109.247:8082/realms/selmag
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  jmx:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: http://192.168.109.247:9411
  tracing:
    sampling:
      probability: 1.0